# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bddbc297cf6f8a77c93d2e49dffcb50c67c8c6ba9b4b6133b1b0e1f30a8d0d86411b74c2b6f7280fe6a383472c5c48393f7c0375ec4317655d1c8b109897098c

test:
  secret_key_base: a7234f947c50fd53346c9186103cce1af42ed10a1266e03960425b6bfb15e1732784bfc0b2e6bd53b9d3b2ee198b179cb3b0d92c138ae69ffe33b731c7f8648b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
